"use client"
import Menu from '@/components/Menu'
import './globals.css'
import { Inter } from 'next/font/google'
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu/>
        {children}
      <ProgressBar height="4px"
        color="#fffd00"
        options={{ showSpinner: false }}
        shallowRouting/>
      </body>
    </html>
  )
}
